# Generated by Django 4.2.20 on 2025-04-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250417_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
